ADprojectteam1/Controllers/StoreSupController.cs
using ADprojectteam1.DB;
using ADprojectteam1.Filter;
using ADprojectteam1.Models;
using ADprojectteam1.Service;
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.DataVisualization.Charting;

namespace ADprojectteam1.Controllers
{
    [StoreSupFilter]
    public class StoreSupController : Controller
    {
        // GET: StoreSup
        public ActionResult PendingInvAdjList()
        {
            List<InventoryAdj> list = new List<InventoryAdj>();
            List<InventoryAdj> list1 = new List<InventoryAdj>();
            list = InventoryAdjData.FindPendingForSup();
            foreach (InventoryAdj invadj in list)
            {
                if (invadj.Quant * invadj.item.Supplier1.UnitPrice <= 250) list1.Add(invadj);
            }
            ViewBag.listInvAdj = list1;
            return View();
        }

        [HttpPost]
        public JsonResult rejectInvAdj(int InvAdjId, string remark)
        {

            InventoryAdjData.RejectInvAdj(InvAdjId, remark);
            object n = new { amt = 0 };
            return Json(n, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult approveInvAdj(int InvAdjId, string remark)
        {

            InventoryAdjData.ApproveInvAdj(InvAdjId, remark);

            ///Add record to stock card
            ///
            InventoryAdj invadj = InventoryAdjData.FindById(InvAdjId);
            Item item = ItemData.GetItemById(invadj.item.Id);
            int balance = StockCardData.GetStockBalanceByItem(item);
            StockCardData.AdjustStockRecord(DateTime.Today,invadj, balance);



            ///
            object n = new { amt = 0 };
            return Json(n, JsonRequestBehavior.AllowGet);
        }

        /////////////////////////////////////////////////////////Trend Report
        public async Task<ActionResult> TrendReport(int itemId)
        {
            Dictionary<int, Dictionary<string, int>> trendlist = (Dictionary<int, Dictionary<string, int>>)Session["trendlist"];
            Item item = ItemData.GetItemById(itemId);
            List<string> monlist = new List<string>();
            Dictionary<string, int> itemsbtrend = new Dictionary<string, int>();
            for (int i = 12; i >= 1; i--)
            {
                string dt = string.Format("{0}/{1}", DateTime.Today.AddMonths(-i).Month, DateTime.Today.AddMonths(-i).Year);
                monlist.Add(dt);

                //Get stockbalance on given month from monthly report
                int stockbalance = MonthlyReportData.GetMonthlyStockbalanceByMonthAndItemId(dt,itemId);
                itemsbtrend.Add(dt, stockbalance);
                
            }

            int[] cons = trendlist[itemId].Values.ToArray();


            int[] prelist = new int[4];
            int[] paralist = new int[13];
            paralist[0] = itemId;
            for (int i = 1; i < 13; i++)
                paralist[i] = cons[i - 1];
            string conshist = string.Join(", ", paralist);
            using (var client = new HttpClient())
            {
                string xValue = conshist;
                

                // send a GET request to the server uri with the data and get the response as HttpResponseMessage object
                HttpResponseMessage res = await client.GetAsync("http://127.0.0.1:5000/model1?x=" + xValue);

                // Return the result from the server if the status code is 200 (everything is OK)
                // should raise exception or error if it's not
                if (res.IsSuccessStatusCode)
                {
                    // pass the result to update the user preference
                    // have to read as string for the data in response.body
                    //pre = Convert.ToInt32(res.Content.ReadAsStringAsync().Result); //if only display one month prediction.
                    string arr = res.Content.ReadAsStringAsync().Result;
                    prelist = arr.Split(',').Select(str => int.Parse(str)).ToArray(); 
                }
                else prelist = new int[4] { 0,0,0,0};
            }


            ViewBag.cons = cons;
            ViewBag.months = monlist.ToArray();
            ViewBag.Item = item;
            ViewBag.sbalance = itemsbtrend.Values.ToArray();
            ViewBag.prediction = prelist;
            return View();
        }

        public ActionResult TrendReportList(string searchStr,int? page)
        {
            List<StockCard> itemlistsc = new List<StockCard>();
            
            Dictionary<int, Dictionary<string, int>> trendlist = new Dictionary<int, Dictionary<string, int>>();
            

            List<string> monlist = new List<string>();
            for (int i = 12; i >= 1; i--)
            {
                string dt = string.Format("{0}/{1}", DateTime.Today.AddMonths(-i).Month, DateTime.Today.AddMonths(-i).Year);
                monlist.Add(dt);
            }

            //////////////////////////////////////////////////////searchbox feature
            List<Item> listitem = ItemData.FindAll();
            List<Item> resultlist = new List<Item>();
            ViewBag.listItem = listitem;


            IPagedList<Item> resultlist1;
            bool match = false;

            if (searchStr == null||searchStr=="")
            {
                searchStr = "";
                resultlist1 = listitem.ToPagedList(page ?? 1, 7);
            }
            else
            {
                foreach (Item Pro in listitem)
                {
                    bool fit = false;
                    if (Search.Found(Pro.Description, searchStr).fit)
                    {
                        fit = true;
                        Pro.Description = Search.Found(Pro.Description, searchStr).str;
                    }

                    if (fit) { match = true; resultlist.Add(Pro); }
                }
                resultlist1 = resultlist.ToPagedList(page ?? 1, 7);
            }

            ViewBag.listitem = resultlist1;

            ViewData["searchStr"] = searchStr;
            ViewData["match"] = match;

            /////////////////////////////////////////////////////////////






            foreach (Item item in resultlist1)
            {
                Dictionary<string, int> itemsbtrend = new Dictionary<string, int>();
                Dictionary<string, int> itemtrend = new Dictionary<string, int>();
                
                foreach (string m in monlist)
                {
                    //Get monthly consumption quant on given month
                    int cons = MonthlyReportData.GetMonthlyConsByMonthAndItemId(m,item.Id);
                    itemtrend.Add(m, cons);
                }
                trendlist.Add(item.Id,itemtrend);
            }

            
            

            ViewBag.trendlist = trendlist;
            ViewBag.monthslist = monlist;
            Session["trendlist"] = trendlist;
            
            return View();
        }

        [HttpPost]
        public JsonResult UpdateReOrderLevel(int itemId, int newreorderlevel)
        {

            ItemData.UpdateReOrderLevelByItemId(itemId,newreorderlevel);

            

            ///
            object n = new { newlevel = newreorderlevel };
            return Json(n, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateReOrderQuant(int itemId, int newreorderquant)
        {

            ItemData.UpdateReOrderQuantByItemId(itemId, newreorderquant);



            ///
            object n = new { newquant = newreorderquant };
            return Json(n, JsonRequestBehavior.AllowGet);
        }

    }
}

ADprojectteam1/Views/StoreSup/PendingInvAdjList.cshtml
@using ADprojectteam1.Models;

@{
    ViewBag.Title = "Pending Inventory Adjustment Vouchour List";
    List<InventoryAdj> listinvadj = ViewBag.listInvAdj;

}

    <div class="row" style="padding-top:0px;">
        <div class="col-sm-3 col-xs-3 col-lg-3 col-md-3">
            @{
                Html.RenderPartial("_Layout_StoreSup_LeftBar");
            }
        </div>

        <div class="w3-main" style="margin-left:250px">
            <h2>Inventory Adjustment List</h2>

            @{if (listinvadj.Count != 0)
                {
                    <table class="w3-table w3-striped">
                        <tr><th>Item Name</th><th>Quantity</th><th>Amount</th><th>Reason</th></tr>

                        @{ foreach (InventoryAdj invadj in listinvadj)
                            {
                                <tr>
                                    <td>@invadj.item.Description</td>
                                    <td>@invadj.Quant</td>
                                    <td>@invadj.getAmount()</td>
                                    <td>@invadj.Reason</td>
                                    <td><input type="text" placeholder="Remark..." size="6" id="remarkbox @invadj.Id"></td>
                                    <td><input type="button" value="Approve" onclick="approveInvAdj(@invadj.Id)" /></td>
                                    <td><input type="button" value="Reject" onclick="rejectInvAdj(@invadj.Id)" /></td>
                                </tr>



                            }
                        }
                    </table>
                    <br>
                            }
                            else { <h4>There is no pending Inventory Adjustment Voucher to be deal with at this moment.</h4>}
            }

            <br>
        </div>
        </div>


            <script>
                function rejectInvAdj(invadj_id) {




                    var remark = document.getElementById("remarkbox " + invadj_id).value

                    var pdata = { InvAdjId: invadj_id, remark: remark };

                    $.ajax({
                        type: "POST",
                        url: "/StoreSup/rejectInvAdj",
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(pdata),
                        dataType: "json",

                        // Response Success
                        success: function (response) {

                            alert("Rejected Inventory Adjustment successfully");
                            window.location.href = "./PendingInvAdjList";

                        },

                        // Response Fail
                        failure: function (response) {
                            alert("Fail Case");
                        },

                        // Response Error
                        error: function (response) {
                            alert("ERROR case");
                        }


                    });
                }

                function approveInvAdj(invadj_id) {




                    var remark = document.getElementById("remarkbox " + invadj_id).value

                    var pdata = { InvAdjId: invadj_id, remark: remark };

                    $.ajax({
                        type: "POST",
                        url: "/StoreSup/approveInvAdj",
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(pdata),
                        dataType: "json",

                        // Response Success
                        success: function (response) {

                            alert("Approved Inventory Adjustment successfully");
                            window.location.href = "./PendingInvAdjList";

                        },

                        // Response Fail
                        failure: function (response) {
                            alert("Fail Case");
                        },

                        // Response Error
                        error: function (response) {
                            alert("ERROR case");
                        }


                    });
                }
            </script>

ADprojectteam1/Views/StoreSup/TrendReport.cshtml
@using ADprojectteam1.Models;


@{
    ViewBag.Title = "TrendReport";
    string[] months= ViewBag.months;
    int[] cons = ViewBag.cons;
    Item item = ViewBag.item;
    int[] sbalance = ViewBag.sbalance;
    int[] prediction = ViewBag.prediction;
}

<div class="row" style="padding-top:0px;">
    <div class="col-sm-3 col-xs-3 col-lg-3 col-md-3">
        @{
            Html.RenderPartial("_Layout_StoreSup_LeftBar");
        }
    </div>

    <div class="w3-main" style="margin-left:250px">
        <h4>Item Info</h4>

        <table class="w3-table w3-striped">
            <tr><th>Category</th><th>Item Code</th><th>Item Decription</th><th>Item UOM</th><th>ReOrder Level</th><th>ReOrder Quant</th></tr>
            <tr><td height="20">@item.Category</td><td>@item.ItemCode</td><td>@item.Description</td><td>@item.UnitofMeasure</td><td><input type="text" size="6" id="reorderlevelBox" value="@item.ReorderLevel"><input type="button" value="Update ReorderLevel" onclick="UpdateReorderLevel(@item.Id);" /></td><td><input type="text" size="6" id="reorderquantBox" value="@item.ReorderQty"><input type="button" value="Update Reorder Quant" onclick="UpdateReorderQuant(@item.Id);" /></td></tr>
            <tr><th></th><th></th><th></th><th>Average Stock Balance</th><th>Average Monthly Consumption</th><th>LSTM Neurol Network Prediction</th></tr>

            <tr><td></td><td></td><td></td><td>@String.Format("{0:0.##}", sbalance.Average())</td><td>@String.Format("{0:0.##}", cons.Average())</td><td>@prediction[1],@prediction[2],@prediction[3]</td></tr>

        </table>

        <h4>Consuming TrendReport</h4>
        <table class="w3-table w3-striped">
            <tr><td>Month</td>
                @{ for (int i = 0; i < months.Length; i++)
                    {
                        <td><span id="months @i">@months[i]</span></td>
}
            }
        </tr>
        <tr><td>Comsumed Quant</td>
            @{ for (int i = 0; i < cons.Length; i++)
                {
                    <td><span id="cons @i">@cons[i]</span></td>
                }
            }
        </tr>
            <tr><td>Stock Balance</td>
            @{ for (int i = 0; i < sbalance.Length; i++)
                {
                    <td><span id="sbalance @i">@sbalance[i]</span></td>
                }
            }
        </tr>
    </table>


    

    <br>
    <br>

    <!-- Styles -->
    <style>
        #chartdiv {
            width: 100%;
            height: 300px;
        }
    </style>

    <!-- Resources -->
    <script src="https://www.amcharts.com/lib/4/core.js"></script>
    <script src="https://www.amcharts.com/lib/4/charts.js"></script>
    <script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>

    <!-- Chart code -->
    <script>
        am4core.ready(function () {

            // Themes begin
            am4core.useTheme(am4themes_animated);
            // Themes end

            // Create chart instance
            var chart = am4core.create("chartdiv", am4charts.XYChart);
            chart.scrollbarX = new am4core.Scrollbar();

            // Add data
           for (x = 0; x < 12; x++) {

                var m = document.getElementById("months " + x).innerHTML

                var c = parseInt(document.getElementById("cons " + x).innerHTML)

                var s = parseInt(document.getElementById("sbalance " + x).innerHTML)
                var obj = { "date": m, "cons": c, "stockbalance":s };
               chart.data.push(obj);
               

            }

            

            // Create axes
            var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis.dataFields.category = "date";
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.renderer.minGridDistance = 60;
            categoryAxis.tooltip.disabled = true;

            var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.renderer.minWidth = 50;
            valueAxis.min = 0;
            valueAxis.cursorTooltipEnabled = false;

            // Create series
            var series = chart.series.push(new am4charts.ColumnSeries());
            series.sequencedInterpolation = true;
            series.dataFields.valueY = "cons";
            series.dataFields.categoryX = "date";
            series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
            series.columns.template.strokeWidth = 0;

            series.tooltip.pointerOrientation = "vertical";

            series.columns.template.column.cornerRadiusTopLeft = 10;
            series.columns.template.column.cornerRadiusTopRight = 10;
            series.columns.template.column.fillOpacity = 0.8;

            // on hover, make corner radiuses bigger
            var hoverState = series.columns.template.column.states.create("hover");
            hoverState.properties.cornerRadiusTopLeft = 0;
            hoverState.properties.cornerRadiusTopRight = 0;
            hoverState.properties.fillOpacity = 1;

            series.columns.template.adapter.add("fill", function (fill, target) {
                return chart.colors.getIndex(target.dataItem.index);
            })

            
            var paretoValueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            paretoValueAxis.renderer.opposite = true;
            paretoValueAxis.min = 0;
            
            paretoValueAxis.strictMinMax = true;
            paretoValueAxis.renderer.grid.template.disabled = true;
            paretoValueAxis.numberFormatter = new am4core.NumberFormatter();
            paretoValueAxis.numberFormatter.numberFormat = "#"
            paretoValueAxis.cursorTooltipEnabled = false;

            var paretoSeries = chart.series.push(new am4charts.LineSeries())
            paretoSeries.dataFields.valueY = "stockbalance";
            paretoSeries.dataFields.categoryX = "date";
            paretoSeries.yAxis = paretoValueAxis;
            paretoSeries.tooltipText = "stockbalance: {valueY.formatNumber('#')}[/]";
            paretoSeries.bullets.push(new am4charts.CircleBullet());
            paretoSeries.strokeWidth = 2;
            paretoSeries.stroke = new am4core.InterfaceColorSet().getFor("alternativeBackground");
            paretoSeries.strokeOpacity = 0.5;

            // Cursor
            chart.cursor = new am4charts.XYCursor();
            chart.cursor.behavior = "panX";

        }); // end am4core.ready()



         function UpdateReorderLevel(item_id) {




                var q = document.getElementById("reorderlevelBox").value

                var pdata = { itemId: item_id, newreorderlevel: q };

                $.ajax({
                    type: "POST",
                    url: "/StoreSup/UpdateReOrderLevel",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(pdata),
                    dataType: "json",

                    // Response Success
                    success: function (response) {

                        alert("Updated Item ReOrder Level successfully");
                        document.getElementById("reorderlevelBox").innerHTML = response.newlevel;

                    },

                    // Response Fail
                    failure: function (response) {
                        alert("Fail Case");
                    },

                    // Response Error
                    error: function (response) {
                        alert("ERROR case");
                    }


                });
        }


        function UpdateReorderQuant(item_id) {




                var q = document.getElementById("reorderquantBox").value

                var pdata = { itemId: item_id, newreorderquant: q };

                $.ajax({
                    type: "POST",
                    url: "/StoreSup/UpdateReOrderQuant",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(pdata),
                    dataType: "json",

                    // Response Success
                    success: function (response) {

                        alert("Updated Item ReOrder Quant successfully");
                        document.getElementById("reorderquantBox").innerHTML = response.newquant;

                    },

                    // Response Fail
                    failure: function (response) {
                        alert("Fail Case");
                    },

                    // Response Error
                    error: function (response) {
                        alert("ERROR case");
                    }


                });
            }
    </script>

    <!-- HTML -->
    <div id="chartdiv"></div>
    </div>
</div>

ADprojectteam1/Views/StoreSup/TrendReportList.cshtml
@using ADprojectteam1.Models;
@using ADprojectteam1.DB;
@using PagedList.Mvc;
@using PagedList;
    <script>
        window.onload = function () { searchEnter() };
    </script>

@{
    ViewBag.Title = "TrendReportList";
    Dictionary<int, Dictionary<string, int>> trendlist = ViewBag.trendlist;
    List<string> mlist = ViewBag.monthslist;
    string searchStr = (string)ViewData["searchStr"];
    bool match = (bool)ViewData["match"];
    PagedList<Item> listItem=ViewBag.listitem;
}

<div class="row" style="padding-top:0px;">
    <div class="col-sm-3 col-xs-3 col-lg-3 col-md-3">
        @{
            Html.RenderPartial("_Layout_StoreSup_LeftBar");
        }
    </div>

    <div class="w3-main" style="margin-left:250px">
        <h2>Item Consumption Trend Report</h2>


        <br>
        <form action="javascript:searchClick()" class="navbar-brand" style="padding-top:7px;" method="post">
            <table>
                <tr>
                    <td>

                        <input type="text" class="form-control" placeholder="Search.." size="20" id="searchBox" value="@searchStr">
                    </td>
                    <td>
                        <button type="submit" class="btn btn-info" style="background-color:darkslategrey;border:none;">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </td>

                </tr>
            </table>
        </form>


        <table class="w3-table w3-striped">
            <tr>
                <th>Item Des</th>
                @{ foreach (string m in mlist)
                    {
                        <th>@m</th>
                    } }
            </tr>

            @{ foreach (int i in trendlist.Keys)
                {
                    <tr>
                        <td>@ItemData.GetItemById(i).Description</td>
                        @{ foreach (string m in mlist)
                            {
                                <td>@trendlist[i][m]</td>
                            }
                        }
                        <td><input type="button" value="More Info" onclick="location.href='@Url.Action("TrendReport", "StoreSup",new { itemId=i})'" /></td>
                    </tr>
                }

            }


        </table>

        @Html.PagedListPager(listItem, page => Url.Action("TrendReportList", new { page, searchStr = searchStr }),new PagedListRenderOptions() { LiElementClasses=new List<string> { "breadcrumb-item"}, UlElementClasses=new List<string> { "breadcrumb"}  })





        <br>
        <br>
    </div>
</div>


<script>

    function searchEnter() {
        var searchBox = document.getElementById("searchBox");
        searchBox.addEventListener("keypress", function (e) {
            var key = e.which || e.keyCode;
            if (key === 13) {
                var data = { searchStr: searchBox.value };  /*Here we pass the Viariable name "searchStr" and its value to dictionary 'data'*/
                doPOST(data);           /*Here we post 'data' to method, if the method has a parameter with same name of "searchStr", it passes to controller.*/
            }
        });
    }

    function searchClick() {
        var searchBox = document.getElementById("searchBox");
        var data = { searchStr: searchBox.value };  /*Here we pass the Viariable name "searchStr" and its value to dictionary 'data'*/

        doPOST(data);
    }

    function doPOST(data) {
        var ajax = new XMLHttpRequest();

        ajax.onreadystatechange = function () {
            if (ajax.readyState == 4) {
                document.open();
                document.write(ajax.response);
                document.close();
            }
        }
        ajax.open("POST", "/StoreSup/TrendReportList", true);
        ajax.setRequestHeader("Content-type", "application/json;charset=UTF-8");

        ajax.send(JSON.stringify(data));
    }
    </script>