ADprojectteam1/Controllers/DepEmpController.cs
using ADprojectteam1.DB;
using ADprojectteam1.Filter;
using ADprojectteam1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ADprojectteam1.Service;
using PagedList;
using PagedList.Mvc;


namespace ADprojectteam1.Controllers
{
    [DepEmpFilter]
    public class DepEmpController : Controller
    {
        // GET: DepEmp
        public ActionResult RequisitionList()
        {
            List<SRequisition> lreq = new List<SRequisition>();
            string user = (string)Session["username"];
            bool dele= EmployeeData.GetDelegateStatusByUserName(user);
            ViewBag.delestatus = dele;
            if (dele) Session["sessionRole"] = "DeleManager";

            lreq = SrequisitionData.FindAllByUsername(user);
            ViewBag.listreq = lreq;
            
            
            return View();
        }

        public ActionResult deleteReq(int id)
        {
            SrequisitionData.deleteReqById(id);

            return RedirectToAction("RequisitionList");
        }

        [HttpPost]
        public JsonResult AddReqItem(int Id,int quant)
        {
            SRequisition sr = new SRequisition();
            Employee user = EmployeeData.FindByUserName((string)Session["username"]);
            int id = user.Id;
            sr = (SRequisition)Session["reqform"];
           
            if (sr == null)
            {
                sr = new SRequisition();
                sr.ListItem = new List<ReqItem>();
                Item p = new Item();
                p = ItemData.GetItemById(Id);
                ReqItem reqitem = new ReqItem(p, user, quant);

                sr.ListItem.Add(reqitem);

            }

            else if (!sr.ListItem.Where(x => x.item.Id == Id).Any())
            {
                Item p = new Item();
                p = ItemData.GetItemById(Id);
                ReqItem reqitem = new ReqItem(p, user, quant);

                sr.ListItem.Add(reqitem);

            }
            else
            {
                ReqItem ri = new ReqItem();
                ri = sr.ListItem.Where(x => x.item.Id == Id).FirstOrDefault();
                ri.Quant = quant;
            }

           



            Session["reqform"] = sr;

            object new_q = new { quant = sr.ListItem.Sum(x => x.Quant) };
            return Json(new_q, JsonRequestBehavior.AllowGet);

        }

        public ActionResult SubmitReqForm()
        {
            SRequisition sr = (SRequisition)Session["reqform"];
            SrequisitionData.SaveReq(sr);
            Employee e = EmployeeData.FindByUserName((string)Session["username"]);
            Employee manager = EmployeeData.FindEmpById(e.department.DepHeadId);

            Task task = Task.Run(() => {
                EmailNotification.SendNotificationEmailToEmployee(manager.EmailAdd,"New Stationary Requisition Reminder","There is a new Stationary Requistion for your approval.");
            });
            
            
            
            Session.Remove("reqform");

            return RedirectToAction("RequisitionList");
        }

    

    public ActionResult RequisitionForm(string searchStr, int? page)
        {
            List<Item> Plist = new List<Item>();
            Plist = ItemData.FindAll();
            ViewBag.listItem = Plist;
            
            List<Item> Rlist = new List<Item>();
            bool match = false;
            
            if (searchStr == null)
            {
                searchStr = "";
                ViewBag.Rlist = Plist.ToPagedList(page ?? 1,7);
            }
            else
            {
                foreach (Item Pro in Plist)
                {
                    bool fit = false;
                    if (Search.Found(Pro.Description, searchStr).fit)
                    {
                        fit = true;
                        Pro.Description = Search.Found(Pro.Description, searchStr).str;
                    }
                    
                    if (fit) { match = true; Rlist.Add(Pro); }
                }
                ViewBag.Rlist = Rlist.ToPagedList(page ?? 1,7);
            }


            ViewData["searchStr"] = searchStr;
            ViewData["match"] = match;


            string user = (string)Session["username"];
            bool dele = EmployeeData.GetDelegateStatusByUserName(user);
            ViewBag.delestatus = dele;
            if (dele) Session["sessionRole"] = "DeleManager";

            return View();
        }



        
    }
}

ADprojectteam1/Controllers/DepRepController.cs
using ADprojectteam1.DB;
using ADprojectteam1.Filter;
using ADprojectteam1.Models;
using ADprojectteam1.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ADprojectteam1.Controllers
{
    [DepRepFilter]
    public class DepRepController : Controller
    {
        public Dictionary<int, int> loadsigninglist()
        {
            Dictionary<int, int> list = new Dictionary<int, int>();
            Employee u = EmployeeData.FindByUserName((string)Session["username"]);
            List<DepOrder> ldo = new List<DepOrder>();
            ldo = DepOrderData.GetCollectedDepOrderByDepId(u.department.Id);
            if (ldo.Any())
            {
                foreach (int itemId in ldo.Select(x => x.item.Id).ToList())
                {
                    list.Add(itemId, ldo.Where(x => x.item.Id == itemId).FirstOrDefault().collectedquant);
                }
            }
            return list;
        }

        // GET: DepRep
        public ActionResult PendingDisbursmentList()
        {
            Dictionary<int, int> signinglist = new Dictionary<int, int>();
            
                signinglist = loadsigninglist();
            ViewBag.Rlist=signinglist;
            Session["signinglist"] = signinglist;

            string user = (string)Session["username"];
            
            
            bool dele = EmployeeData.GetDelegateStatusByUserName(user);
            if (dele) Session["sessionRole"] = "DeleManager";
            ViewBag.delestatus = dele;

            ViewBag.dep = DepartmentData.GetDepById(EmployeeData.FindDepIdByUsername(user)); 

            return View();
        }

        [HttpPost]
        public JsonResult ChangeReceiveQuant(int itemId, int quant)
        {
            Dictionary<int, int> signinglist = new Dictionary<int, int>();
            if (Session["signinglist"] != null)
            { signinglist = (Dictionary<int, int>)Session["signinglist"]; }
            else
            {
                signinglist = loadsigninglist();
            }

            if (signinglist.ContainsKey(itemId))
            {
                signinglist[itemId] = quant;
            }
            int totalq = signinglist.Values.Sum();
            Session["signinglist"] = signinglist;

            object new_amount = new { Id = itemId, quant = totalq };

            return Json(new_amount, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ConfirmReceive()
        {
            

            //load the signinglist
            Dictionary<int, int> signinglist = new Dictionary<int, int>();
            if (Session["signinglist"] != null)
            { signinglist = (Dictionary<int, int>)Session["signinglist"]; }
            else
            {
                throw new Exception("please sign in to confirm receivement");
            }

            int depId;
            if (Session["username"] != null)
            {
                Employee u = EmployeeData.FindByUserName((string)Session["username"]);
                depId = u.department.Id;
            }
            else
            {
                throw new Exception("please sign in to confirm receivement"); 
            }


            bool notifystatus = false;
                foreach (int itemId in signinglist.Keys)
                {
                    

                   // SRequisition sr = new SRequisition();
                    //sr.ListItem = new List<ReqItem>();
                        
                foreach (int empId in DepartmentData.GetDepById(depId).Employees.Select(x => x.Id))
                    {
                    if (ReqItemData.SetReqItemDeliveredToRep(empId, itemId) && notifystatus == false)
                    {
                        string emailaddress = EmployeeData.FindEmpById(empId).EmailAdd;
                        Task task = Task.Run(() =>
                        {
                            EmailNotification.SendNotificationEmailToEmployee(emailaddress,"Stationary Requisition Status Changed", "Your Stationary Requisition has delivered to Department Representative.");
                        });
                        notifystatus = true;
                    }
                }


                //if any discrepancy, create new reqItem to replenish in next delivery.
                int dif = DepOrderData.GetDeliveringOrderByDepAndItem(depId, itemId).quant- signinglist[itemId];

                if (dif>0)                    {

                    int i = itemId;
                    int j = DepartmentData.GetRepById(depId);
                    ReqItemData.CreatReqItem(itemId, DepartmentData.GetRepById(depId), dif,"approved");
                    /////////////////////////
                    }

                //mark this DepOrder to be delivered
                DepOrderData.SetReceived(depId, itemId, signinglist[itemId]);


            }
            Session.Remove("signinglist");
            


            object new_amount = new { };

            return Json(new_amount, JsonRequestBehavior.AllowGet);
        }

        ///////////////////////Manage Collecting Point
        public ActionResult ManageCollectingPoint()
        {
            List<string> listCP = new List<string>() { "Stationery Store-Administration Building(9:30am)","Management School(11:00am)","Medical School(9:30am)","Engineering School(11:00am)","Science School(9:30am)","University Hospital(11:00am)"};
            Employee emp = EmployeeData.FindByUserName((string)Session["username"]);
            Department dep = DepartmentData.GetDepById(emp.department.Id);
            
            ViewBag.currentDep = dep;
            ViewBag.listCP = listCP;

            string user = (string)Session["username"];
            bool dele = EmployeeData.GetDelegateStatusByUserName(user);
            if (dele) Session["sessionRole"] = "DeleManager";
            ViewBag.delestatus = dele;

            return View();
        }

        [HttpPost]
        public JsonResult ChangeCollectingPoint(string cp)
        {
            Employee emp = EmployeeData.FindByUserName((string)Session["username"]);
            Department dep = DepartmentData.GetDepById(emp.department.Id);

            DepartmentData.SetColPoint(dep.Id, cp);

            object new_amount = new {cp=cp };

            return Json(new_amount, JsonRequestBehavior.AllowGet);
        }
    }
}

ADprojectteam1/Controllers/StoreManagerController.cs
using ADprojectteam1.DB;
using ADprojectteam1.Filter;
using ADprojectteam1.Models;
using ADprojectteam1.Service;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ADprojectteam1.Controllers
{
    [StoreManagerFilter]
    public class StoreManagerController : Controller
    {
        // GET: StoreManager
        public ActionResult PendingInvAdjList()
        {
            List<InventoryAdj> list = new List<InventoryAdj>();
            List<InventoryAdj> list1 = new List<InventoryAdj>();
            list = InventoryAdjData.FindPendingForSup();
            foreach (InventoryAdj invadj in list)
            {
                if (invadj.Quant * invadj.item.Supplier1.UnitPrice > 250) list1.Add(invadj);
            }
            ViewBag.listInvAdj = list1;
            return View();
        }

        [HttpPost]
        public JsonResult rejectInvAdj(int InvAdjId, string remark)
        {

            InventoryAdjData.RejectInvAdj(InvAdjId, remark);
            object n = new { amt = 0 };
            return Json(n, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult approveInvAdj(int InvAdjId, string remark)
        {

            InventoryAdjData.ApproveInvAdj(InvAdjId, remark);

            ///Add record to stock card
            ///
            InventoryAdj invadj = InventoryAdjData.FindById(InvAdjId);
            Item item = ItemData.GetItemById(invadj.item.Id);
            int balance = StockCardData.GetStockBalanceByItem(item);
            StockCardData.AdjustStockRecord(DateTime.Today, invadj, balance);



            ///
            object n = new { amt = 0 };
            return Json(n, JsonRequestBehavior.AllowGet);
        }


        /////////////////////////////////////////////////////////////////////Manage Suppliers
        public ActionResult ManageSupplier()
        {
            List<Supplier> slist = new List<Supplier>();
            
            slist = SupplierData.FindAllSupplier();
            
            ViewBag.slist = slist;
            return View();
        }

        public ActionResult EditSupplier(int sid)
        {
            Supplier sup = SupplierData.GetSupplierById(sid);
            ViewBag.sup = sup;
            return View();
        }

        public ActionResult UpdateSupplierInfo(Supplier sup)
        {

            if (sup != null) {
                SupplierData.UpdateSupplier(sup);
            }
            return RedirectToAction("ManageSupplier");

            
        }

        public ActionResult EditSupplierPrice(int sid,string searchStr, int? page)
        {
            

            //////////////////////////////////////////////////////searchbox feature
            List<Item> listitem = ItemData.FindAll();

            ViewBag.listItem = listitem;
            IPagedList<Item> pagedlist;
            List<Item> resultlist = new List<Item>();
            
            bool match = false;

            if (searchStr == null)
            {
                searchStr = "";
                pagedlist = listitem.ToPagedList(page ?? 1, 7);
            }
            else
            {
                foreach (Item Pro in listitem)
                {
                    bool fit = false;
                    if (Search.Found(Pro.Description, searchStr).fit)
                    {
                        fit = true;
                        Pro.Description = Search.Found(Pro.Description, searchStr).str;
                    }

                    if (fit) { match = true; resultlist.Add(Pro); }
                }
                pagedlist = resultlist.ToPagedList(page ?? 1, 7);
            }

            ViewBag.Rlist = pagedlist;
            ViewData["searchStr"] = searchStr;
            ViewData["match"] = match;

            /////////////////////////////////////////////////////////////
            
            List<ItemSupplier> rlist = new List<ItemSupplier>();
            List<ItemSupplier> list = ItemSupplierData.GetAllBySupplierId(sid);
            foreach (Item item in pagedlist)
            {

                rlist.Add(list.Where(x=>x.item.Id==item.Id).FirstOrDefault());
            }

            ViewBag.listitemsup = rlist;
            return View();
        }

        [HttpPost]
        public JsonResult UpdatePrice(int isId, double newprice)
        {

            ItemSupplierData.SetPriceById(isId,newprice);



            ///
            object n = new { Id=isId, nprice=newprice };
            return Json(n, JsonRequestBehavior.AllowGet);
        }
    }
}

ADprojectteam1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        html, body, h1, h2, h3, h4, h5 {
            font-family: "Open Sans", sans-serif
        }
    </style>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body class="w3-theme-l5">
    @{
        Html.RenderPartial("_Layout_Header");
    }

    <div class="container-fluid body-content">
        <div class="container-fluid">

            <div class="row" style="padding-top:10px;">

                @RenderBody()
            </div>

        </div>
        <hr />
        <footer style="text-align:center;">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>

ADprojectteam1/Views/Shared/_Layout_DepManager_LeftBar.cshtml
<!-- Sidebar -->
    <nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
        <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
            <i class="fa fa-remove"></i>
        </a>
        <h4 class="w3-bar-item"><b>Menu</b></h4>
        <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("PendingRequisitionList", "DepManager")">Pending Requisition</a>
        <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("ManageRep", "DepManager")">Representative Management</a>
        
        @{if (((string)Session["sessionRole"]).Equals("DepManager")) {<a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("DelegateView", "DepManager")">Delegate Management</a>
                }
            }
        <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("MonthlyBill", "DepManager")">Monthly Bill</a>
    </nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<script>
    // Get the Sidebar
    var mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    var overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
            overlayBg.style.display = "none";
        } else {
            mySidebar.style.display = 'block';
            overlayBg.style.display = "block";
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
        overlayBg.style.display = "none";
    }
</script>

ADprojectteam1/Views/Shared/_Layout_DepRep_LeftBar.cshtml
@{ bool dele = ViewBag.delestatus;}

<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
        <i class="fa fa-remove"></i>
    </a>
    <h4 class="w3-bar-item"><b>Menu</b></h4>
    <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("PendingDisbursmentList","DepRep")">Pending Disbursment List</a>
    <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("ManageCollectingPoint","DepRep")">Collecting Point Management</a>
    @{if (@dele)
        {<a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("PendingRequisitionList", "DepManager")">Delegate Role</a>}
    }
    
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<script>
    // Get the Sidebar
    var mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    var overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
            overlayBg.style.display = "none";
        } else {
            mySidebar.style.display = 'block';
            overlayBg.style.display = "block";
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
        overlayBg.style.display = "none";
    }
</script>

ADprojectteam1/Views/Shared/_Layout_Emp_LeftBar.cshtml
@{ bool dele = ViewBag.delestatus;}

<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
        <i class="fa fa-remove"></i>
    </a>
    <h4 class="w3-bar-item"><b>Menu</b></h4>
    <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("RequisitionList", "DepEmp")">Requisition List</a>
    <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("RequisitionForm", "DepEmp")">Create New Requisition</a>
    @{if (@dele)
        {<a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("PendingRequisitionList", "DepManager")">Delegate Role</a>}
        }

    
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<script>
    // Get the Sidebar
    var mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    var overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
            overlayBg.style.display = "none";
        } else {
            mySidebar.style.display = 'block';
            overlayBg.style.display = "block";
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
        overlayBg.style.display = "none";
    }
</script>

ADprojectteam1/Views/Shared/_Layout_Header.cshtml
<!-- Navbar -->
<div class="w3-top">
    <div class="w3-bar w3-theme-d2 w3-left-align w3-large">
        <a href="#" class="w3-bar-item w3-button w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>Shawn's University Logistic System</a>
        
        <nobr>

            @{
                if (Session["username"] == null)
                {

                    
                }
                else
                {
                    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
                    
                    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="News"><i class="fa fa-globe"></i></a>
                    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Account Settings"><i class="fa fa-user"></i></a>
                    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Messages"><i class="fa fa-envelope"></i></a>
                    
                    <a href="@Url.Action("Logout", "Home")" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">

                    <i class="glyphicon glyphicon-log-out"></i>
                    </a>
                    
                    
                }
            }
        </nobr>
        
    </div>
</div>

ADprojectteam1/Views/Shared/_Layout_StoreClerk_LeftBar.cshtml
<!-- Sidebar -->
    <nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
        <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
            <i class="fa fa-remove"></i>
        </a>
        <h4 class="w3-bar-item"><b>Menu</b></h4>
        <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("TobeCollectList","StoreClerk")">To be collected List</a>
        <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("GenerateDelOrder","StoreClerk")">Orders to be delivered</a>
        <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("TobeReOrderList","StoreClerk")">Short stock balance</a>
        <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("ManagePO","StoreClerk")">Purchase Order Management</a>
        <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("InvAdjForm","StoreClerk")">Inventory Adjustment</a>
    </nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<script>
    // Get the Sidebar
    var mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    var overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
            overlayBg.style.display = "none";
        } else {
            mySidebar.style.display = 'block';
            overlayBg.style.display = "block";
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
        overlayBg.style.display = "none";
    }
</script>

ADprojectteam1/Views/Shared/_Layout_StoreManager_LeftBar.cshtml
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
        <i class="fa fa-remove"></i>
    </a>
    <h4 class="w3-bar-item"><b>Menu</b></h4>
    <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("PendingInvAdjList","StoreManager")">Pending Inventory Adjustment List</a>
    <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("ManageSupplier","StoreManager")">Manage Suppliers</a>
    
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<script>
    // Get the Sidebar
    var mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    var overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
            overlayBg.style.display = "none";
        } else {
            mySidebar.style.display = 'block';
            overlayBg.style.display = "block";
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
        overlayBg.style.display = "none";
    }
</script>

ADprojectteam1/Views/Shared/_Layout_StoreSup_LeftBar.cshtml
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
        <i class="fa fa-remove"></i>
    </a>
    <h4 class="w3-bar-item"><b>Menu</b></h4>
    <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("PendingInvAdjList","StoreSup")">Pending Inventory Adjustment List</a>
    <a class="w3-bar-item w3-button w3-hover-black" href="@Url.Action("TrendReportList","StoreSup")">Trend analysis Report</a>
    
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<script>
    // Get the Sidebar
    var mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    var overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
            overlayBg.style.display = "none";
        } else {
            mySidebar.style.display = 'block';
            overlayBg.style.display = "block";
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
        overlayBg.style.display = "none";
    }
</script>